fix: replace GCC builtins in tests with C++20 std equivalents for MSVC
2 error in tests with MSVC:

B:\build\ninfer-all>ninja -C build-win11 -k 0
ninja: Entering directory `build-win11'
[3/5] Building CXX object tests\CMakeFiles\...est.dir\ops\test_hadamard_transform.cpp.ob
FAILED: [code=2] tests/CMakeFiles/ninfer_hadamard_transform_test.dir/ops/test_hadamard_transform.cpp.obj
"C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x64\cl.exe"  /nologo /TP -DNINFER_SM8X_COMPAT=1 -DNINFER_TMA_STAGED_DESCRIPTORS=1 -DNOMINMAX -DWIN32_LEAN_AND_MEAN -Dmain=ninfer_bundle_entry_ninfer_hadamard_transform_test -IB:\build\ninfer-all\include -IB:\build\ninfer-all\src -IB:\build\ninfer-all\tests -external:I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4\include" -external:I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4\include\cccl" -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD /Zc:preprocessor /Zc:__cplusplus /utf-8 /we4715 /we4716 /showIncludes /Fotests\CMakeFiles\ninfer_hadamard_transform_test.dir\ops\test_hadamard_transform.cpp.obj /Fdtests\CMakeFiles\ninfer_hadamard_transform_test.dir\ /FS -c B:\build\ninfer-all\tests\ops\test_hadamard_transform.cpp
B:\build\ninfer-all\tests\ops\test_hadamard_transform.cpp(45): error C3861: “__builtin_popcount”: identifier not found
[4/5] Building CXX object tests\CMakeFiles\....dir\models\qwen3_5\test_vision_cpu.cpp.ob
FAILED: [code=2] tests/CMakeFiles/ninfer_qwen3_5_vision_cpu_test.dir/models/qwen3_5/test_vision_cpu.cpp.obj
"C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x64\cl.exe"  /nologo /TP -DNINFER_SM8X_COMPAT=1 -DNINFER_TMA_STAGED_DESCRIPTORS=1 -DNOMINMAX -DUTF8PROC_STATIC -DWIN32_LEAN_AND_MEAN -Dmain=ninfer_bundle_entry_ninfer_qwen3_5_vision_cpu_test -IB:\build\ninfer-all\include -IB:\build\ninfer-all\src -IB:\build\ninfer-all\tests -external:I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4\include" -external:I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.4\include\cccl" -external:IB:\build\ninfer-all\third_party -external:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD /Zc:preprocessor /Zc:__cplusplus /utf-8 /we4715 /we4716 /showIncludes /Fotests\CMakeFiles\ninfer_qwen3_5_vision_cpu_test.dir\models\qwen3_5\test_vision_cpu.cpp.obj /Fdtests\CMakeFiles\ninfer_qwen3_5_vision_cpu_test.dir\ /FS -c B:\build\ninfer-all\tests\models\qwen3_5\test_vision_cpu.cpp
B:\build\ninfer-all\tests\models\qwen3_5\test_vision_cpu.cpp(284): error C2065: “M_PI”: undeclared identifier
ninja: build stopped: cannot make progress due to previous errors.